# Inserts a blank line between shell prompts
add_newline = false

[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

[python]
format = '- [py ${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = "bold green"

[golang]
format = "- [go ($version) ]($style)"

[rust]
format = "- [rust $version ]($style)"
style = "bold green"

[package]
disabled = true